---

- name: configure authselect
  template:
    src: 'etc/authselect/authselect.conf.j2'
    dest: '/etc/authselect/authselect.conf'
    owner: 'root'
    group: 'root'
    mode: '0640'
    when: ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version == "8") 


- name: configure passwd-auth
  template:
    src: 'etc/authselect/password-auth.j2'
    dest: '/etc/authselect/password-auth'
    owner: 'root'
    group: 'root'
    mode: '0640'
    when: ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version == "8")


- name: configure system-auth
  template:
    src: 'etc/authselect/system-auth.j2'
    dest: '/etc/authselect/system-auth'
    owner: 'root'
    group: 'root'
    mode: '0640'
    when: ansible_facts.os_family == 'RedHat' and ansible_facts.distribution_major_version == "8")




