---

- name: create gdm3 directory
  file:
    path:  /etc/gdm3
    state: directory



- name: configure greeter
  template:
    src: 'etc/gdm3/greeter.dconf-defaults.j2'
    dest: '/etc/gdm3/greeter.dconf-defaults'
    owner: 'root'
    group: 'root'
    mode: '0640'
