---

- name: configure user issues
  template:
    src: 'etc/issue.j2'
    dest: '/etc/issue'
    owner: 'root'
    group: 'root'
    mode: '0640'

- name: configure user issue.net
  template:
    src: 'etc/issue.net.j2'
    dest: '/etc/issue.net'
    owner: 'root'
    group: 'root'
    mode: '0640'

