---
- name: add pinerolo_profile.sh to profile.d
  template:
    src: 'etc/profile.d/profile.conf.j2'
    dest: '/etc/profile.d/pinerolo_profile.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'
  when: not os_security_kernel_enable_core_dump | bool

- name: remove pinerolo_profile.sh from profile.d
  file:
    path: /etc/profile.d/pinerolo_profile.sh
    state: absent
  when: os_security_kernel_enable_core_dump | bool

- name: configure default profile
  template:
    src: 'etc/profile.j2'
    dest: '/etc/profile'
    owner: 'root'
    group: 'root'
    mode: '0750'
    
- name: add colorgrep.csh and sh to profile.d
  template:
    src: 'etc/profile.d/colorgrep.csh.j2'
    dest: '/etc/profile.d/colorgrep.csh'
    owner: 'root'
    group: 'root'
    mode: '0750'
  
  template:
    src: 'etc/profile.d/colorgrep.sh.j2'
    dest: '/etc/profile.d/colorgrep.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'
  
   
- name: add colorzgrep.csh and sh to profile.d
  template:
    src: 'etc/profile.d/colorzgrep.csh.j2'
    dest: 'etc/profile.d/colorzgrep.csh'
    owner: 'root'
    group: 'root'
    mode: '0750'

  template:
    src: 'etc/profile.d/colorzgrep.sh.j2'
    dest: 'etc/profile.d/colorzgrep.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'


- name: add colorls.csh and sh to profile.d
  template:
    src: 'etc/profile.d/colorls.csh.j2'
    dest: 'etc/profile.d/colorls.csh'
    owner: 'root'
    group: 'root'
    mode: '0750'

  template:
    src: 'etc/profile.d/colorls.sh.j2'
    dest: 'etc/profile.d/colorls.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'

- name: add colorxzgrep.csh and sh to profile.d
  template:
    src: 'etc/profile.d/colorxzgrep.csh.j2'
    dest: 'etc/profile.d/colorxzgrep.csh'
    owner: 'root'
    group: 'root'
    mode: '0750'

  template:
    src: 'etc/profile.d/colorxzgrep.sh.j2'
    dest: 'etc/profile.d/colorxzgrep.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'

- name: add gawk.csh and sh to profile.d
  template:
    src: 'etc/profile.d/gawk.csh.j2'
    dest: 'etc/profile.d/gawk.csh'
    owner: 'root'
    group: 'root'
    mode: '0750'

  template:
    src: 'etc/profile.d/gawk.sh.j2'
    dest: 'etc/profile.d/gawk.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'


- name: add lang.csh and sh to profile.d
  template:
    src: 'etc/profile.d/lang.csh.j2'
    dest: 'etc/profile.d/lang.csh'
    owner: 'root'
    group: 'root'
    mode: '0750'

  template:
    src: 'etc/profile.d/lang.sh.j2'
    dest: 'etc/profile.d/lang.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'



- name: add less.csh and sh to profile.d
  template:
    src: 'etc/profile.d/less.csh.j2'
    dest: 'etc/profile.d/less.csh'
    owner: 'root'
    group: 'root'
    mode: '0750'

  template:
    src: 'etc/profile.d/less.sh.j2'
    dest: 'etc/profile.d/less.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'

- name: add vim.csh and sh to profile.d
  template:
    src: 'etc/profile.d/vim.csh.j2'
    dest: 'etc/profile.d/vim.csh'
    owner: 'root'
    group: 'root'
    mode: '0750'

  template:
    src: 'etc/profile.d/vim.sh.j2'
    dest: 'etc/profile.d/vim.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'

- name: add wish2.csh and sh to profile.d
  template:
    src: 'etc/profile.d/wish2.csh.j2'
    dest: 'etc/profile.d/wish2.csh'
    owner: 'root'
    group: 'root'
    mode: '0750'

  template:
    src: 'etc/profile.d/wish2.sh.j2'
    dest: 'etc/profile.d/wish2.sh'
    owner: 'root'
    group: 'root'
    mode: '0750'
    
