---

- name: install sudo package | package-10
  package:
    name: '{{ sudo_package }}'
    state: 'present'


- name: configure sudoers 
  template:
    src: 'etc/sudoers.j2'
    dest: '/etc/sudoers'
    owner: 'root'
    group: 'root'
    mode: '0640'

